# Generated by Django 3.0.4 on 2020-03-27 17:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200327_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
