# Generated by Django 3.0.4 on 2020-03-27 17:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed_media', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
