# Generated by Django 3.0.7 on 2020-06-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='title',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.Specialization'),
            preserve_default=False,
        ),
    ]
